import type { College } from '@/types';

export const SEEDED_COLLEGES: College[] = [
  {
    id: 'col-iitb',
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    state: 'Maharashtra',
    country: 'India',
    student_count: 38,
    total_score: 14250,
  },
  {
    id: 'col-iitd',
    name: 'Indian Institute of Technology Delhi',
    slug: 'iit-delhi',
    state: 'Delhi',
    country: 'India',
    student_count: 35,
    total_score: 13800,
  },
  {
    id: 'col-iitm',
    name: 'Indian Institute of Technology Madras',
    slug: 'iit-madras',
    state: 'Tamil Nadu',
    country: 'India',
    student_count: 32,
    total_score: 12900,
  },
  {
    id: 'col-iitk',
    name: 'Indian Institute of Technology Kanpur',
    slug: 'iit-kanpur',
    state: 'Uttar Pradesh',
    country: 'India',
    student_count: 28,
    total_score: 11400,
  },
  {
    id: 'col-iitkgp',
    name: 'Indian Institute of Technology Kharagpur',
    slug: 'iit-kharagpur',
    state: 'West Bengal',
    country: 'India',
    student_count: 29,
    total_score: 10850,
  },
  {
    id: 'col-iitr',
    name: 'Indian Institute of Technology Roorkee',
    slug: 'iit-roorkee',
    state: 'Uttarakhand',
    country: 'India',
    student_count: 25,
    total_score: 9600,
  },
  {
    id: 'col-bits',
    name: 'Birla Institute of Technology and Science, Pilani',
    slug: 'bits-pilani',
    state: 'Rajasthan',
    country: 'India',
    student_count: 30,
    total_score: 11950,
  },
  {
    id: 'col-nitt',
    name: 'National Institute of Technology Tiruchirappalli',
    slug: 'nit-trichy',
    state: 'Tamil Nadu',
    country: 'India',
    student_count: 24,
    total_score: 8900,
  },
  {
    id: 'col-nitk',
    name: 'National Institute of Technology Karnataka, Surathkal',
    slug: 'nit-surathkal',
    state: 'Karnataka',
    country: 'India',
    student_count: 22,
    total_score: 8450,
  },
  {
    id: 'col-nitw',
    name: 'National Institute of Technology Warangal',
    slug: 'nit-warangal',
    state: 'Telangana',
    country: 'India',
    student_count: 20,
    total_score: 7800,
  },
  {
    id: 'col-iiith',
    name: 'International Institute of Information Technology, Hyderabad',
    slug: 'iiit-hyderabad',
    state: 'Telangana',
    country: 'India',
    student_count: 31,
    total_score: 13200,
  },
  {
    id: 'col-iiitb',
    name: 'International Institute of Information Technology, Bangalore',
    slug: 'iiit-bangalore',
    state: 'Karnataka',
    country: 'India',
    student_count: 19,
    total_score: 7500,
  },
  {
    id: 'col-dtu',
    name: 'Delhi Technological University',
    slug: 'dtu-delhi',
    state: 'Delhi',
    country: 'India',
    student_count: 26,
    total_score: 9200,
  },
  {
    id: 'col-nsut',
    name: 'Netaji Subhas University of Technology',
    slug: 'nsut-delhi',
    state: 'Delhi',
    country: 'India',
    student_count: 21,
    total_score: 7900,
  },
  {
    id: 'col-vit',
    name: 'Vellore Institute of Technology, Vellore',
    slug: 'vit-vellore',
    state: 'Tamil Nadu',
    country: 'India',
    student_count: 42,
    total_score: 10400,
  },
  {
    id: 'col-ju',
    name: 'Jadavpur University',
    slug: 'jadavpur-university',
    state: 'West Bengal',
    country: 'India',
    student_count: 18,
    total_score: 7100,
  },
  {
    id: 'col-rgpv',
    name: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal',
    slug: 'rgpv-bhopal',
    state: 'Madhya Pradesh',
    country: 'India',
    student_count: 27,
    total_score: 8150,
  },
  {
    id: 'col-coep',
    name: 'College of Engineering, Pune',
    slug: 'coep-pune',
    state: 'Maharashtra',
    country: 'India',
    student_count: 17,
    total_score: 6950,
  },
];
